//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmarTrashDBContext : DbContext
    {
        public SmarTrashDBContext()
            : base("name=SmarTrashDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblBinType> tblBinType { get; set; }
        public virtual DbSet<tblCategory> tblCategory { get; set; }
        public virtual DbSet<tblCity> tblCity { get; set; }
        public virtual DbSet<tblCurrentThrow> tblCurrentThrow { get; set; }
        public virtual DbSet<tblGift> tblGift { get; set; }
        public virtual DbSet<tblGiftCompetition> tblGiftCompetition { get; set; }
        public virtual DbSet<tblOrder> tblOrder { get; set; }
        public virtual DbSet<tblProduct> tblProduct { get; set; }
        public virtual DbSet<tblScanProduct> tblScanProduct { get; set; }
        public virtual DbSet<tblSpecificBin> tblSpecificBin { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
        public virtual DbSet<tblWeight> tblWeight { get; set; }
        public virtual DbSet<tblSelectedMonthGift> tblSelectedMonthGift { get; set; }
    }
}
