//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCurrentThrow
    {
        public int ThrowNumber { get; set; }
        public System.DateTime DateThrow { get; set; }
        public double ThrowWeight { get; set; }
        public short ThrowPoints { get; set; }
        public Nullable<int> BinQRId { get; set; }
        public string UserEmail { get; set; }
    
        public virtual tblSpecificBin tblSpecificBin { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
