//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSelectedMonthGift
    {
        public int IdMonthGift { get; set; }
        public byte MonthGift { get; set; }
        public int YearGift { get; set; }
    
        public virtual tblGift tblGift { get; set; }
    }
}
