//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSpecificBin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSpecificBin()
        {
            this.tblCurrentThrow = new HashSet<tblCurrentThrow>();
        }
    
        public int BinQRId { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public string Address { get; set; }
        public Nullable<int> BinTypeId { get; set; }
        public Nullable<int> WeightId { get; set; }
    
        public virtual tblBinType tblBinType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCurrentThrow> tblCurrentThrow { get; set; }
        public virtual tblWeight tblWeight { get; set; }
    }
}
